import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// LUCKY BOSS — FIREBASE CONFIGURATION (job seeker app)
///
/// Normally generated by `flutterfire configure`, which requires console
/// access to the Firebase project. We do not have that access, so these values
/// are transcribed by hand:
///
/// - **Android** from `android/app/google-services.json`, the client block for
///   package `com.userapp.luckyboss`. The Android `applicationId` was renamed
///   from `com.userapp.luckyboss_jobseeker` to match it, because the console
///   entry could not be changed from our side and a mismatch fails the Gradle
///   build outright.
/// - **Web** from the Laravel `.env` (`FIREBASE_APP_ID`, `FIREBASE_API_KEY`,
///   `FIREBASE_AUTH_DOMAIN`). **These web values are unverified** — they are
///   not in the JSON we were given, and nobody has confirmed the web app
///   actually exists in the console. If Chrome sign-in fails with
///   `auth/invalid-api-key` or `auth/configuration-not-found`, that is why, and
///   the fix is a real config from the project owner, not a code change.
///
/// Firebase API keys are not secrets. They identify the project, they do not
/// authorise anything; access is controlled by the Firebase security rules and,
/// here, by Laravel verifying the resulting ID token server-side. Committing
/// them is the documented, expected practice.
///
/// iOS is deliberately absent: there is no `GoogleService-Info.plist` for this
/// project, so an iOS build throws a clear error here rather than failing
/// somewhere deep inside the Firebase SDK with no explanation.
class DefaultFirebaseOptions {
  DefaultFirebaseOptions._();

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'Firebase is not configured for iOS/macOS. The project owner must add '
          'an Apple app in the Firebase console and supply GoogleService-Info.plist.',
        );
      default:
        throw UnsupportedError(
          'Firebase is not configured for $defaultTargetPlatform.',
        );
    }
  }

  /// From google-services.json, client[1] — package com.userapp.luckyboss.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIqaS9NX_hNPWMvOVehnaBC8cask2GxlI',
    appId: '1:655783263537:android:d67362e44445bf4d158410',
    messagingSenderId: '655783263537',
    projectId: 'luckyboss-617d2',
    storageBucket: 'luckyboss-617d2.firebasestorage.app',
  );

  /// Unverified — see the class docstring.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtJpQWHICsqtYljEwFpjweM6AWx-r-w8g',
    appId: '1:655783263537:web:cfe4a6c244d88b7e158410',
    messagingSenderId: '655783263537',
    projectId: 'luckyboss-617d2',
    authDomain: 'luckyboss-617d2.firebaseapp.com',
    storageBucket: 'luckyboss-617d2.firebasestorage.app',
    measurementId: 'G-Q1CP691KL8',
  );
}
